[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["__pycache__", ".venv"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
