name: CI - Backend
on:
  pull_request:
    paths:
      - "backend/**"
  push:
    branches: [main]
    paths:
      - "backend/**"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt
      - name: Smoke test
        run: |
          python - <<'PY'
          import requests, threading, time, uvicorn
          from app.main import app
          def run():
              uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")
          t=threading.Thread(target=run, daemon=True); t.start()
          time.sleep(1)
          import urllib.request, json
          data = json.loads(urllib.request.urlopen("http://127.0.0.1:8000/api/health").read())
          assert data.get("status")=="ok"
          PY
